const products = [
  {
    id: 1,
    name: "Дракон ролл",
    categoryId: 1,
    composition: "Угорь, огурец, авокадо, соус унаги",
    description: "Роскошный ролл с угрем и авокадо сверху.",
    price: 500,
    isDiscount: false,
    discountName: null,
    calculatedPrice: null,
  },
  {
    id: 2,
    name: "Маки ролл1",
    categoryId: 2,
    composition: "Рис, лосось",
    description: "Классика!",
    price: 300,
    isDiscount: true,
    discountName: "День защитника отечества",
    calculatedPrice: 231,
  },
  {
    id: 3,
    name: "Дракон ролл",
    categoryId: 3,
    composition: "Угорь, огурец, авокадо, соус унаги",
    description: "Роскошный ролл с угрем и авокадо сверху.",
    price: 500,
    isDiscount: false,
    discountName: null,
    calculatedPrice: null,
  },
  {
    id: 4,
    name: "Маки ролл1",
    categoryId: 4,
    composition: "Рис, лосось",
    description: "Классика!",
    price: 300,
    isDiscount: true,
    discountName: "День защитника отечества",
    calculatedPrice: 231,
  },
  {
    id: 5,
    name: "Дракон ролл",
    categoryId: 5,
    composition: "Угорь, огурец, авокадо, соус унаги",
    description: "Роскошный ролл с угрем и авокадо сверху.",
    price: 500,
    isDiscount: false,
    discountName: null,
    calculatedPrice: null,
  },
  {
    id: 6,
    name: "Маки ролл1",
    categoryId: 6,
    composition: "Рис, лосось",
    description: "Классика!",
    price: 300,
    isDiscount: true,
    discountName: "День защитника отечества",
    calculatedPrice: 231,
  },
];

export default products;
